### ISSUE TITLE
Revisión por pares

### ISSUE THREAD

**Issue by matigomez1611** [SoleSmith/mercadoLiebre-SoleSmith#1]
1. Respecto a la estructura del sitio visualizar que contenga estos elementos cada
sección:

Header:
Logo: Cumple, se visualiza el logo en todas las resoluciones.
Barra de búsqueda: Cumple. Sugiero cambiar el atributo value por placeholder.
Comprá en cuotas y sin tarjeta de crédito: Cumple
Barra de navegación: Cumple, se visualiza en las resoluciones correspondientes a tablet y desktop, y para mobile un icono que representa un menú de tipo hamburguesa.
Ofertas: Cumple.
Tiendas Oficiales: Cumple
Vender: Cumple
Ayuda: Cumple
Login: Cumple, se visualiza y además acompañado de un icono.
Registro: Cumple, se visualiza y además acompañado de un icono.
Mis compras: Cumple, se visualiza y además acompañado de un icono.

Main:
Sección basada en las últimas visitas: Cumple, se visualiza la cantidad de columnas acorde a las resoluciones planteadas en el proyecto
Sección de ofertas: Cumple de la misma forma que la sección anterior.

Footer:
Pagá con tarjeta o en efectivo: Cumple, el texto se encuentra centrado y con sus respectivos iconos y los colores indicados.
Envío gratis desde $ 2.500: Cumple, el texto se encuentra centrado y con sus respectivos iconos y los colores indicados.
Seguridad, de principio a fin: Cumple, el texto se encuentra centrado y con sus respectivos iconos y los colores indicados.
Copyright © 1999-2022 MercadoLiebre S.R.L.: Cumple, se visualiza al final de la página

2. Haciendo foco en los estilos del pie de página (Footer):
¿El contenido de todos los artículos está centrado? Cumple, el contenido se visualiza correctamente centrado.
¿Los íconos tienen un tamaño de 2em y un margen inferior de separación de 10 píxeles?: Cumple con el margen inferior, no cumple con el tamaño. El tamaño del icono se debe asignar con la propiedad font-size: 2em
3. ¿El sitio se adapta a distintas resoluciones de pantalla? Cumple, el sitio se adapta correctamente a las resoluciones planteadas por el cliente.
4. ¿El sitio cuenta con un formulario de registro de usuarios? Cumple, se puede acceder al mismo a través de la barra de navegación.
5. ¿El sitio cuenta con un formulario de login? Cumple, se puede acceder al mismo a través de la barra de navegación.
6. ¿Se muestran mensajes de error cuando un usuario coloca información
equivocada en un campo de los formularios? Cumple, se visualizan mensajes de error.
7. ¿El search bar es un formulario? Cumple, el search bar es un formulario.
8. ¿Se utilizan animaciones y propiedades de transición de CSS? Cumple, se muestran sombras y el título del producto al pasar el cursor sobre un artículo
9. Para terminar el feedback, menciona algunas cosas que crees que tu
compañero hizo bien. Código legible y bien organizado, los formularios están muy bien logrados y particularmente me gusto mucho el diseño de los botones.
10. Por último, menciona algo que tu compañero podría mejorar.

**Comment by SoleSmith** [comment]
Muchas gracias Mati por tu revisión:
1- Header: Barra de búsqueda: Cumple. Sugiero cambiar el atributo value por placeholder. **Corregido**
2- Haciendo foco en los estilos del pie de página (Footer):
¿Los íconos tienen un tamaño de 2em y un margen inferior de separación de 10 píxeles?: Cumple con el margen inferior, no cumple con el tamaño. El tamaño del icono se debe asignar con la propiedad font-size: 2em. **Corregido**

**Comment by SoleSmith** [comment]
Commits realizadas para los cambios sugeridos: 
[issue-change barra busqueda header-register.html](https://github.com/SoleSmith/mercadoLiebre-SoleSmith/commit/8d7bf9386d85949bc87f939df2b02c892656eee6)

[issue-change barra de busqueda-header-home.html](https://github.com/SoleSmith/mercadoLiebre-SoleSmith/commit/10b30ec701d8e1b3ecf42a29e1f5686869be3f22)- Es el del login

[issue-change barra de busqueda-header-home.html](https://github.com/SoleSmith/mercadoLiebre-SoleSmith/commit/6795512e4341901954854da3d56f3aa5189c1683)
