### ISSUE TITLE
Agregar transición en tarjeta de producto

### ISSUE THREAD

**Issue by gabrieldominguezdh10** [SoleSmith/mercadoLiebre-SoleSmith#2]
Se debe agregar una transición a la hora de mostrar información adicional al hacer hover en las tarjetas de productos.

Tarjeta sin hover:
![image](https://github.com/SoleSmith/mercadoLiebre-SoleSmith/assets/147005581/8edc2fd4-2d96-4ef9-a626-05558487199a)

Tarjeta con hover:
![image](https://github.com/SoleSmith/mercadoLiebre-SoleSmith/assets/147005581/98cbb808-3c78-4d6d-a2ec-84d581501c3d)

**Comment by SoleSmith** [comment]
realizado!
