### ISSUE TITLE
Agregar animación del icono del camión

### ISSUE THREAD

**Issue by gabrieldominguezdh10** [SoleSmith/mercadoLiebre-SoleSmith#3]
Se debe agregar animación de cambio de orientación al icono del camión de las tarjetas de productos al hacer hover sobre la tarjeta.

Icono del camión no "apunta" hacia arriba al hacer hover:
![image](https://github.com/SoleSmith/mercadoLiebre-SoleSmith/assets/147005581/15a72b70-de56-4ac3-bf8d-7d79629b0dab)

**Comment by SoleSmith** [comment]
realizado!
