### ISSUE TITLE
Verificar la ubicación y ancho de elementos en ciertos anchos de dispositivos

### ISSUE THREAD

**Issue by gabrieldominguezdh10** [SoleSmith/mercadoLiebre-SoleSmith#4]
- Acomodar de mejor manera los elementos de la barra de navegación

- Verificar el ancho del body (se ve una columna blanca en el ancho del navegador que no deberia ir)

![image](https://github.com/SoleSmith/mercadoLiebre-SoleSmith/assets/147005581/45770b26-8b24-49a2-9717-e41d33443061)

**Comment by SoleSmith** [comment]
realizado!
